lint: {}
nf_core_version: 3.4.1
repository_type: pipeline
template:
  author: Benjamin Wehnert & Max Stammnitz
  description: "Until now, most Deep Mutational Scanning (DMS) experiments relied\
    \ on variant-specific barcoded libraries for sequencing. This method enabled DMS\
    \ on large proteins and led to many great publications. Recently, efforts have\
    \ increased to make use of the classic and more simple random fragmentation-based\
    \ short-read sequencing (\u201Cshotgun-sequencing\u201D). This saves time and\
    \ money and due to its simpler experimental design is less prone to mistakes.\
    \ dmscore handles the essential computational steps, processing the raw FASTQ\
    \ files and generating a count table of variants. Along the way, it provides multiple\
    \ QC metrics, enabling users to quickly evaluate the success of their experimental\
    \ setup."
  force: false
  is_nfcore: true
  name: deepmutscan
  org: nf-core
  outdir: .
  version: 1.0.0
