name: "counts_to_fitness"
description: Reformats the library-filtered variant count table into a standardized TSV compatible with downstream fitness calculation tools, ensuring mutation nomenclature is consistent with the reference sequence.
keywords:
  - deep mutational scanning
  - dms
  - variant counting
  - format conversion
  - fitness
tools:
  - "mutscan":
      description: "R package for analysis of deep mutational scanning data"
      homepage: "https://bioconductor.org/packages/release/bioc/html/mutscan.html"
      documentation: "https://bioconductor.org/packages/release/bioc/manuals/mutscan/man/mutscan.pdf"
      tool_dev_url: "https://github.com/csoneson/mutscan"
      doi: "10.1186/s12859-023-05187-y"
      licence: ["GPL-3.0-or-later"]
  - "bioconductor-biostrings":
      description: "Efficient manipulation of biological strings"
      homepage: "https://bioconductor.org/packages/Biostrings"
      licence: ["Artistic-2.0"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - variantCounts_filtered_by_library:
        type: file
        description: CSV file containing variant counts already filtered against the design library
        pattern: "*.{csv}"
  - - wt_seq:
        type: file
        description: FASTA file containing the wild-type DNA reference sequence
        pattern: "*.{fasta,fa}"
  - - pos_range:
        type: string
        description: Start and stop codon positions (ORF) in the format 'start-stop'

output:
  - fitness_input:
      - meta:
          type: map
          description: Groovy Map containing sample information
      - "${meta.id}_fitness_input.tsv":
          type: file
          description: A standardized TSV file ready for input into fitness calculation modules
          pattern: "*_fitness_input.tsv"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@BenjaminWehnert1008"
  - "@MaximilianStammnitz"
