name: "gatk_saturationmutagenesis"
description: Uses GATK AnalyzeSaturationMutagenesis to identify and quantify variants from premerged reads in a Deep Mutational Scanning (DMS) experiment.
keywords:
  - variant calling
  - dms
  - gatk
  - saturation mutagenesis
  - counting
tools:
  - "gatk4":
      description: "Genome Analysis Toolkit (GATK) for variant discovery and high-throughput sequencing analysis"
      homepage: "https://gatk.broadinstitute.org/hc/en-us"
      documentation: "https://gatk.broadinstitute.org/hc/en-us/articles/360037593731-AnalyzeSaturationMutagenesis-BETA"
      licence: ["BSD-3-Clause"]
  - "samtools":
      description: "Tools for manipulating next-generation sequencing data"
      homepage: "http://www.htslib.org/"
      documentation: "http://www.htslib.org/doc/samtools.html"
      licence: ["MIT/Expat"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - premerged_reads:
        type: file
        description: BAM/SAM file containing premerged reads
        pattern: "*.{bam,sam}"
  - - wt_seq:
        type: file
        description: FASTA file containing the wild-type reference sequence
        pattern: "*.{fasta,fa}"
  - - pos_range:
        type: string
        description: Start and stop codon positions (ORF) in format 'start-stop'
  - - min_counts:
        type: integer
        description: Minimum number of variant observations required to report a variant

output:
  - variantCounts:
      - meta:
          type: map
          description: Groovy Map containing sample information
      - gatk_output.variantCounts:
          type: file
          description: The primary GATK output file containing mutation counts
          pattern: "*.variantCounts"
  - gatk_output:
      - meta:
          type: map
          description: Groovy Map containing sample information
      - gatk_output.*:
          type: file
          description: All files generated by the GATK AnalyzeSaturationMutagenesis command
          pattern: "gatk_output.*"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@BenjaminWehnert1008"
  - "@MaximilianStammnitz"
